[workspace]
resolver = "2"
members = ["blockstore", "cli", "node", "node-wasm", "proto", "rpc", "types"]

[workspace.dependencies]
lumina-node = { version = "0.1.0", path = "node" }
lumina-node-wasm = { version = "0.1.0", path = "node-wasm" }
celestia-proto = { version = "0.1.0", path = "proto" }
celestia-rpc = { version = "0.1.0", path = "rpc", default-features = false }
celestia-types = { version = "0.1.0", path = "types", default-features = false }
libp2p = "0.53.1"
nmt-rs = { git = "https://github.com/S1nus/nmt-rs.git", branch="cnode/tm-hash", features=["serde"]}
#nmt-rs = {path = "../nmt-rs", features=["serde"]}
tendermint = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "bbe7de8", default-features = false }
tendermint-proto = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "bbe7de8" }
blockstore = { version = "0.1.0", path = "blockstore" }

[patch.'https://github.com/eigerco/celestia-tendermint-rs.git']
# Uncomment to apply local changes
#tendermint = { path = "../celestia-tendermint-rs/tendermint" }
#tendermint-proto = { path = "../celestia-tendermint-rs/proto" }

#[patch.'https://github.com/eigerco/nmt-rs.git']
# Uncomment to apply local changes
#nmt-rs = { path = "../nmt-rs" }
